import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


const PageLayout = ({children, title= 'News App'}) => {
  return (
    <>
        <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            header navbar
        </header>
        <main className={styles.main}>
            {children}
        </main>
        <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        </footer>
        <style jsx>{`
            header {
                padding: 1.5rem;
                background: black;
                color:white;
                margin-bottom:1rem;
                }
            main, footer {
                margin: 1.5rem;
            }
            `}
        </style>
    </>
  )
}

export default PageLayout