import Head from 'next/head'
import '../styles/globals.css'

// npm i next@12 react@17 react-dom@17 eslint-config-next@12

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </> 
  )
  
}

export default MyApp
